name: pytorch_example
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - mlflow>=1.0
    - Cython
    - matplotlib>=3.2.2
    - numpy>=1.18.5
    - opencv-python>=4.1.2 
    - Pillow 
    - PyYAML>=5.3 
    - scipy>=1.4.1 
    - tensorboard>=2.2 
    - torch>=1.6.0 
    - torchvision>=0.7.0 
    - tqdm>=4.41.0

